service: aws-node-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MORALIS_API_KEY: "replace_me"

functions:
  getNativeBalance:
    handler: functions/getNativeBalance.handler
  getWalletNfts:
    handler: functions/getWalletNfts.handler
