dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"
dotenv: .env
networks:
  default: development
  goerli:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
